// Generated by CoffeeScript 1.9.3
$(function() {
  var code_current, code_default, code_reset, code_run, editor;
  code_default = "<html>\n	<style>\n		h1 {\n			color:black;\n			font-family: \"Times New Roman\";\n		}\n\n		h3 {\n			color:black;\n			font-family: \"Times New Roman\";\n		}\n\n		body {\n			background-color:white;\n			text-align: center;\n		}\n	</style>\n\n	<body>\n		<h1>My Super Special Awesome Website</h1>\n		<h3>I'm having the best summer at Stanford University!</h3>\n		<img src=\"http://chasemcniel.weebly.com/uploads/1/4/5/4/14541026/8394649.png\" id=\"stanford\">\n	</body>\n</html>";
  code_run = function() {
    var code_text;
    code_text = editor.getValue();
    window.frames[0].document.body.innerHTML = code_text;
    return localStorage.setItem('code_current', code_text);
  };
  code_reset = function() {
    localStorage.clear();
    localStorage.setItem('code_current', code_default);
    editor.getSession().setValue(code_default);
    return window.frames[0].document.body.innerHTML = code_default;
  };
  if (!localStorage.getItem('code_current')) {
    localStorage.setItem('code_current', code_default);
  }
  editor = ace.edit('editor');
  editor.setTheme('ace/theme/twilight');
  editor.getSession().setMode('ace/mode/html');
  code_current = localStorage.getItem('code_current');
  editor.getSession().setValue(code_current);
  editor.setOptions({
    fontSize: "9pt"
  });
  window.frames[0].document.body.innerHTML = code_current;
  editor.getSession().on("change", function() {
    return code_run();
  });
  $("#button_reset").on("click", function() {
    return code_reset();
  });
  return $("#button_run").on("click", function() {
    return code_run();
  });
});
